routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', 'CourseController@index')->name('home');

Route::get('/course/{id}', 'CourseController@course');

Route::resource('admin/posts', 'Admin\\PostsController');

Route::get('/detail/{course}/{page}', 'DetailController@index');


Route::get('/exam/{course}/{type}/{page}', 'ExamController@index');

Route::post('/exam/save/{course}', 'ExamController@saveExam');

Route::get('/seachdata/{id}', 'SeachDataController@index');

Route::resource('user','UserController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username','name','nickname','emp_code', 'password','delete','type'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use App\course;
use App\Detail;
use App\UserDetail;
use App\ExamCourse;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
        /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::where('delete',0)->latest()->get();
        return view('user.index',compact('user'));
           
    }
   
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }
  
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $request->validate([
            'emp_code' => ['required'],
            'username' => ['required', 'string', 'max:255'],
            'name' => ['required', 'string', 'max:255'],
            'nickname' => ['required', 'string'],
            'password' => ['required', 'string', 'min:6'],
            'type' => ['required'],
        ]);

  
        User::create([
            'emp_code' => $request['emp_code'],
            'username' => $request['username'],
            'name' => $request['name'],
            'nickname' => $request['nickname'],
            'type' => $request['type'],
            'password' => Hash::make($request['password']),
        ]);
   
        return redirect()->route('user.index')
                        ->with('success','เพิ่มข้อมูลของ '. $request['name'] .' เรียบร้อยแล้ว');
    }
   
    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {

        $course = course::where('child_in','=',null)->get();

        foreach ($course as $courses) {
            $detailCurrent = $this->currentPage($courses->id,$user->id);

            if($detailCurrent == 1){
                $detailCurrent = 0;
            }

            $courses->currentPage = number_format(($detailCurrent*100)/$courses->page_full,0);
            $courses->currentString = 'width:'.$courses->currentPage.'%';
            $courses->examType = null;

            if($courses->child == 8){
                $courses->exam =  $this->example($courses->child,$user->id);
                $courses->examType = 2;
            }else{
                $courses->exam =  $this->example($courses->id,$user->id);
            }

            
            $type = ExamCourse::select('type')->where('course_id',$courses->id)->limit(1)->get()->toArray();
            foreach ($type as $value) {
                $courses->examType = $value['type'];
            }
        }

        return view('user.show',compact('user','course'));
    }
   

    private function example($course,$user){
        $exam = ExamCourse::where('course_id',$course)->get();
        $currentURL = url('/');
        foreach ($exam as $key=>$value) {
            $test = ExamCourse::find($value->id)
            ->User()
            ->wherePivot('users_id',$user)
            ->get()
            ->toArray();

            if($value->type == 1){
                foreach ($test as $testIn) 
                {
                        $value->source = $testIn['pivot']['source'];
                        $value->sales = $testIn['pivot']['sales'];
                        $value->side = $testIn['pivot']['side'];
                        $value->customer_voice = $testIn['pivot']['customer_voice'];
                        $value->related = $testIn['pivot']['related'];
                }
                $value->image = '/images/workshop1.jpg';
            }else{
                $i = 1;
                foreach ($test as $testIn) 
                {
                        $value->result = $currentURL.'/images/customer_ser3_test/result/'.$i.'.jpg';
                        $value->source = $testIn['pivot']['source'];
                        $i++;
                }  
            }
        }
        return $exam;
    }


    private function currentPage($courseId,$userId){
        $pageCurrent = null;
        $pageCurrent =  UserDetail::select('detail_id')
        ->where('user_id',$userId)
        ->where('course_id',$courseId)
        ->orderBy('detail_id', 'desc')
        ->limit(1)
        ->get();

        if(count($pageCurrent) == 0){
           return  $pageCurrent = 1;
        }

        foreach ($pageCurrent as $page) {
            $pageIn = $page->detail_id;
            $pageThis =  Detail::find($page->detail_id);
            return $pageThis->page;
        }
        
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('user.edit',compact('user'));
    }
  
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $request->validate([
            // 'emp_code' => ['required', 'number'],
            'username' => ['required', 'string', 'max:255'],
            'name' => ['required', 'string', 'max:255'],
            'nickname' => ['required', 'string'],
            // 'password' => ['required', 'string', 'min:6'],
            // 'type' => ['required'],
        ]);
  
        if($request['password']){
            $user->username = $request['username'];
            $user->name = $request['name'];
            $user->nickname = $request['nickname'];
            // $user->type = $request['type'];
            $user->password = Hash::make($request['password']);
           
        }else{
            $user->username = $request['username'];
            $user->name = $request['name'];
            // $user->type = $request['type'];
            $user->nickname = $request['nickname'];
        }
        
        $user->save();
        $link = 'home';

        if(auth::user()->type == 1){
            $link = 'user.index';
        }



        return redirect()->route($link)
                        ->with('success','แก้ไขข้อมูลของ '. $user->name .' เรียบร้อยแล้ว');

    }
  
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        // $user->delete();
        $user->delete = 1;
        $user->save();

        return redirect()->route('user.index')
                        ->with('success','User deleted successfully');
    }

}

resources/views/user/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Add New user</h2>
        </div>
        <div class="pull-right">
            <a class="btn btn-primary" href="{{ route('user.index') }}">กลับสู่หน้าจัดการผู้ใช้งาน</a>
        </div>
    </div>
</div>
   <br>
@if ($errors->any())
    <div class="alert alert-danger">
        <strong>Whoops!</strong> มีบางอย่างผิดพลาดโปรดตรวจสอบ<br><br>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
   
<form action="{{ route('user.store') }}" method="POST">
    @csrf
  
     <div class="row">
         <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>รหัสพนักงาน:</strong>
                <input type="number" name="emp_code" class="form-control" placeholder="รหัสพนักงาน">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>ชื่อจริง:</strong>
                <input type="text" name="name" class="form-control" placeholder="ชื่อจริง">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>ชื่อเข้าใช้งาน:</strong>
                    <input type="text" name="username" class="form-control" placeholder="ชื่อเข้าใช้งาน (กรุณากรอกเป็นภาษาอังกฤษ)">
                </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>ชื่อเล่น:</strong>
                    <input type="text" name="nickname" class="form-control" placeholder="ชื่อเล่น">
                </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>สิทธิ์การเข้าถึง : </strong>
                    <label class="radio-inline">
                            <input type="radio" value="1" name="type" >Admin
                          </label>
                          <label class="radio-inline">
                            <input type="radio" value="2" name="type" checked>User
                          </label>
                </div>
        </div>
  


        <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>รหัสผ่าน:</strong>
                    <input type="password" name="password" class="form-control" placeholder="รหัสผ่าน (กรุณาระบุอย่างน้อย 6 ตัว)">
                </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
                <button type="submit" class="btn btn-primary">ยืนยัน</button>
        </div>
    </div>
   
</form>
</div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>แก้ไขผู้ใช้งาน</h2>
            </div>
            @if(Auth::user()->type == 1 )
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('user.index') }}"> กลับสู่หน้าจัดการผู้ใช้งาน</a>
            </div>
            @endif
        </div>
    </div>
   <br>
    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> มีบางอย่างผิดพลาดโปรดตรวจสอบ.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
  
    <form action="{{ route('user.update',$user->id) }}" method="POST">
        @csrf
        @method('PUT')
   
         <div class="row">
                <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>รหัสพนักงาน:</strong>
                            <input type="number"  value="{{ $user->emp_code }}" name="emp_code" class="form-control" placeholder="รหัสพนักงาน" disabled>
                        </div>
                    </div>
            <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <strong>ชื่อจริง:</strong>
                        <input type="text" name="name" value="{{ $user->name }}" class="form-control" placeholder="ชื่อจริง">
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>ชื่อเข้าใช้งาน:</strong>
                            <input type="text" name="username" value="{{ $user->username }}" class="form-control" placeholder="ชื่อเข้าใช้งาน (กรุณากรอกเป็นภาษาอังกฤษ)">
                        </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>ชื่อเล่น:</strong>
                            <input type="text" name="nickname"  value="{{ $user->nickname }}" class="form-control" placeholder="ชื่อเล่น">
                        </div>
                </div>
                @if(Auth::user()->type == 1 )
                <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>สิทธิ์การเข้าถึง : </strong>
                            <label class="radio-inline">
                                    <input type="radio" value="1" name="type" {{ $user->type == '1' ? 'checked' : ''}} >Admin
                                  </label>
                                  <label class="radio-inline">
                                    <input type="radio" value="2" name="type"  {{ $user->type == '2' ? 'checked' : ''}} >User
                                  </label>
                        </div>
                </div>
                 @endif
                <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>รหัสผ่าน:</strong>
                            <input type="password" name="password"  class="form-control" placeholder="ถ้าไม่เปลี่ยนรหัสผ่านไม่ต้องกรอก">
                        </div>
                </div>

            <div class="col-xs-12 col-sm-12 col-md-12 text-center">
              <button type="submit" class="btn btn-primary">บันทึกข้อมูล</button>
            </div>
        </div>
   
    </form>
</div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>จัดการพนักงาน</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-success" href="{{ route('user.create') }}">เพิ่มพนักงาน</a>
                
            </div>
        </div>
    </div>
    <br>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif
   
    <table class="table table-bordered">
        <tr>
            <th>หมายเลข</th>
            <th>ชื่อจริง</th>
            <th>ชื่อเข้าสู่ระบบ</th>
            <th width="280px">ชื่อเล่น</th>
            <th width="380px"></th>
        </tr>
        @foreach ($user as $user)
        <tr>
            <td>{{ $user->emp_code }}</td>
            <td>{{ $user->name }}</td>
            <td>{{ $user->username }}</td>
            <td>{{ $user->nickname }}</td>

            <td>
                <form action="{{ route('user.destroy',$user->id) }}" method="POST">
   
                    <a class="btn btn-info" href="{{ route('user.show',$user->id) }}">แสดงรายละเอียด</a>

 
    
                    <a class="btn btn-primary" href="{{ route('user.edit',$user->id) }}">แก้ไข</a>
   
                    @csrf
                    @method('DELETE')
      
                    <button type="submit" class="btn btn-danger">ลบผู้ใช้งาน</button>
                </form>
            </td>
        </tr>
        @endforeach
    </table>
  
</div>
      
@endsection

resources/views/user/show.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> แสดงรายละเอียดพนักงาน</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('user.index') }}"> กลับสู่หน้าจัดการผู้ใช้งาน</a>
            </div>
        </div>
    </div>
   <br>
   <div class="card">
        <div class="card-body">
            <div class="row"> 
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-6" align="right"><h5><strong>รหัสพนักงาน:</strong></h5></div>
                            <div class="col-sm-6"> <h5>{{ $user->emp_code }}</h5></div>
                        </div>
                    </div>
                </div>    
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-6" align="right"><h5><strong>ชื่อจริง:</strong></h5></div>
                            <div class="col-sm-6"> <h5>{{ $user->name }}</h5></div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                    <div class="form-group">
                        <div class="row">
                            <div class="col-sm-6" align="right"><h5><strong>ชื่อเข้าใช้งาน:</strong></h5></div>
                            <div class="col-sm-6" > <h5>{{ $user->username }}</h5></div>
                        </div>
                    </div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-6" align="right"><h5><strong>ชื่อเล่น:</strong></h5></div>
                                <div class="col-sm-6"> <h5>  {{ $user->nickname }}</h5></div>
                            </div>
                        </div>
                </div>
            </div>
        </div> 
    </div>
    <br>
    <table class="table table-bordered">
        <thead>
          <tr  align="center">
            <th>#</th>
            <th>ชื่อบทเรียน</th>
            <th>ติดตามบทเรียน</th>
          </tr>
        </thead>
        <tbody>
            @foreach ($course as $key => $course)
                <tr>
                    <td style="width:5%">{{$key + 1}}</td>
                    <td style="width:35%">{{$course->desc}}</td>
                    <td style="width:60%">
                        <div class="progress">
                            <div class="progress-bar bg-success" role="progressbar" style="{{$course->currentString}}"  aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">{{$course->currentPage}}%</div>
                        </div>
                        <br>
                        @if($course->currentPage == 100 && $course->test ||
                            $course->currentPage == 100 && $course->child == 8)
                            <button class="btn  btn-success" role="button" data-toggle="modal" data-target="#modal-view-{{ $course->id }}"> คลิกเพื่อดูผลการทดสอบ </button>
                        @endif
                        
                    </td>

                  </tr>

                       <!-- The Modal -->
         <div class="modal fade" id="modal-view-{{ $course->id }}" tabIndex="-1">
                <div class="modal-dialog modal-lg">
                <div class="modal-content">
                
                    <!-- Modal Header -->
                    <div class="modal-header">
                    <h4 class="modal-title"></h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    
                    <!-- Modal body -->
                    
                    <div class="modal-body">
                    
                        @if($course->examType == 1)
                        <div class="card-header" align="center">
                             <strong><h5>คำตอบของ {{$user->name}}</h5></strong>
                        </div>
                        <div class="card-body"> 
                            <div class="row">
                                <div class="col-sm-4" >เสียงของลูกค้า</div>
                                <div class="col-sm-2" >ที่มา</div>
                                <div class="col-sm-1" >ด้านขาย/ด้านบริการ</div>
                                <div class="col-sm-1" >ด้านบวก(+) ด้านลบ (-)</div>
                                <div class="col-sm-2" >แนวทางการนำเสียงลูกค้าไปใช้</div>
                                <div class="col-sm-2" >ฝ่ายที่เกี่ยวข้อง</div>
                            </div>
                            @foreach($course->exam as $key => $exams)
                            <div class="row">
                                    <div class="col-sm-4" >{{$key + 1}} {{$exams->desc}}</div>
                                    <div class="col-sm-2" >{{$exams->source}}</div>
                                    <div class="col-sm-1" >{{$exams->sales}}</div>
                                    <div class="col-sm-1" >{{$exams->side}}</div>
                                    <div class="col-sm-2" >{{$exams->customer_voice}}</div>
                                    <div class="col-sm-2" >{{$exams->related}}</div>
                            </div>
                            @endforeach
                        </div>  
                        @else
                        @foreach ($course->exam as $exams)
                        
                       <div class="card mb-3" align="left">
                                    <div class="card-header" align="center">
                                    <strong><h5>เฉลยคำตอบข้อที่ {{$exams->id - 5}}</h5></strong>
                                    </div>
                                    <div class="card-body"> 
                                        <img src="{{$exams->result}}" class="img-fluid" alt="Responsive image">
                                    </div>
                                </div>
            
                                <div class="card mb-3" align="center">
                                        <div class="card-header" >
                                                    <strong><h5>คำตอบของคุณ</h5></strong>
                                        </div>
                                        <div class="card-body"> 
                                            <h2>{{$exams->source}}</h2>
                                        </div>
                                    </div>
                             @endforeach
                        @endif
                    </div>
                    
                    <!-- Modal footer -->
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                    
                </div>
                </div>
            </div>
            @endforeach
        </tbody>
      </table>
</div>
@endsection