routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/', 'CourseController@index')->name('home');

Route::get('/course/{id}', 'CourseController@course');

Route::resource('admin/posts', 'Admin\\PostsController');

Route::get('/detail/{course}/{page}', 'DetailController@index');


Route::get('/exam/{course}/{type}/{page}', 'ExamController@index');

Route::post('/exam/save/{course}', 'ExamController@saveExam');

Route::get('/seachdata/{id}', 'SeachDataController@index');

Route::resource('user','UserController');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Course</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
    
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">


    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">


    <style>
        body {font-family: Arial, Helvetica, sans-serif;
        }
        * {box-sizing: border-box;}
        
        /* Button used to open the chat form - fixed at the bottom of the page */
        .open-button {
          background-color: #555;
          color: white;
          padding: 16px 20px;
          border: none;
          cursor: pointer;
          opacity: 0.8;
          position: fixed;
          bottom: 23px;
          right: 28px;
          width: 280px;
        }
        
        /* The popup chat - hidden by default */
        .chat-popup {
          display: none;
          font-size: 15px;
          position: fixed;
          bottom: 0;
          right: 15px;
          border: 3px solid #f1f1f1;
          z-index: 9;
        }
        
        .uiSeach {
          list-style-type:circle;
          position: static;
          margin-left: -20px;
        }

        /* Add styles to the form container */
        .form-container {
          max-width: 350px;
          padding: 10px;
          background-color: white;
        }
        
        /* Full-width textarea */
        .form-container textarea {
          width: 100%;
          padding: 15px;
          margin: 5px 0 22px 0;
          border: none;
          background: #f1f1f1;
          resize: none;
          min-height: 30px;
        }
        
        /* When the textarea gets focus, do something */
        .form-container textarea:focus {
          background-color: #ddd;
          outline: none;
        }
        
        /* Set a style for the submit/send button */
        .form-container .btn {
          background-color: #4CAF50;
          color: white;
          padding: 16px 20px;
          border: none;
          cursor: pointer;
          width: 100%;
          margin-bottom:10px;
          opacity: 0.8;
        }
        
        /* Add a red background color to the cancel button */
        .form-container .cancel {
          background-color: red;
        }
        
        /* Add some hover effects to buttons */
        .form-container .btn:hover, .open-button:hover {
          opacity: 1;
        }

        .btn:focus, .btn:active, button:focus, button:active {
            outline: none !important;
            box-shadow: none !important;
          }
          
          #image-gallery .modal-footer{
            display: block;
          }
          
          .thumb{
            margin-top: 15px;
            margin-bottom: 15px;
          }

          .css-color{
            background-color: #e02128;
          }
          .navbar-light .navbar-brand{
            color: #f1f1f1;
          }
          .navbar-light .navbar-nav .nav-link{
            color: #f1f1f1;
          }

          .album.py-5.bg-light {
            background-color: #777777 !important;
        }

        .progress-bar.progress-bar-striped.progress-bar-animated {
          background-color: #e02128 !important;
      }
        </style>

        
</head>
<body>
    <div id="app ">
        <nav class="navbar navbar-expand-md  navbar-light navbar-laravel css-color">
            <div class="container ">
                
                <a class="navbar-brand" href="{{ url('/') }}">
                  <img src="{{ url('/images/logo0001.png') }}" style="width: 63px;">
               </a>
                {{--  <a class="navbar-brand" href="{{ url('/') }}">
                   Course
                </a>  --}}
                
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    @guest
                    @else
                    <ul class="navbar-nav mr-auto">
                        @if(Auth::user()->type == 1)
                            <a class="nav-link" href="{{ url('/user') }}">
                                จัดการผู้ใช้งาน
                                
                             </a>
                        @endif   
                            <a class="nav-link" href="{{ url('/') }}">
                                    คอร์สเรียน
                            </a>
                    </ul>
                    @endguest
                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link"  href="{{ route('login') }}">{{ __('ลงชื่อเข้าใช้งาน') }}</a>
                            </li>
                            {{-- @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('ลงทะเบียนเข้าใช้งาน') }}</a>
                                </li>
                            @endif --}}
                        @else
                                <a class="nav-link" id="messages-tab" href="{{ route('user.show',Auth::user()->id) }}" role="button" >
                                    {{ Auth::user()->name }} 
                                </a>
                                <a class="nav-link" id="messages-tab" href="{{ route('user.edit',Auth::user()->id) }}" role="button" >
                                  แก้ไขโปรไฟล์

                              </a>
                                <a class="nav-link" id="messages-tab" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('ออกจากระบบ') }}
                                    </a>
                                    
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>     
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
        
       

    </div>
</body>
</html>